
var compilers = require("../"),
    path = require("path"),
    fs = require("fs"),
    files = fs.readdirSync(path.join(__dirname, "fixtures"));

function test(file) {
  var locals = { greeting: "Hello" },
      name = file.replace(/\.js$/g, "");

  describe(name, function() {
    it("should compile correctly", function(next) {
      var p = path.join(__dirname, "fixtures", file),
          test = require(p),
          compiler = compilers(name);

      compiler(test.input, locals, function(err, compiled) {
        try {
          // Strip "generated by" as versions will change
          compiled = compiled.replace(/\/\/[^\n\r]*generated by[^\n\r]*\n/gi, "");
          compiled.should.equal(test.output);
          next();
        } catch (err) {
          console.log(compiled);
          next(err);
        }
      });
    });

  });
};

files.forEach(test);
